version: "3.8"
services:

  polardb-redis:
    image: "redis:6"
    container_name: "polardb-redis"
    ports:
      - 6379:6379

  polardb-catalog:
    image: "postgres:13"
    container_name: "polardb-catalog"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=polardb_catalog
    networks:
      - backend

  catalog-service:
    image: "fabricio211/catalog-service:0.0.1-SNAPSHOT"
    container_name: "catalog-service"
    ports:
      - "8001:8001"
      - "9001:9001"
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8001
      - SPRING_DATASOURCE_URL=jdbc:postgresql://polardb-catalog:5432/polardb_catalog
    networks:
      - backend

  order-service:
    image: fabricio211/order-service:2.0.0
    container_name: order-service
    ports:
      - 9003:9003
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - backend

  polardb-order:
    image: "postgres:13"
    container_name: "polardb-order-postgresql"
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=polardb_order
    networks:
      - backend

networks:
  backend:
    driver: bridge